version: '3.7'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Formula1!"
      MSSQL_PID: "Express"
    ports:
        - "1434:1433"